worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /usuarios/api/ {
            proxy_pass http://servicio_usuarios:3001/api/;
            proxy_set_header Host $host;
        }

        location /rutas/api/ {
            proxy_pass http://servicio_rutas:3002/api/;
            proxy_set_header Host $host;
        }

        location /tracking/api/ {
            proxy_pass http://servicio_tracking:3003/api/;
            proxy_set_header Host $host;
        }

        location /pagos/api/ {
            proxy_pass http://servicio_pagos:3004/api/;
            proxy_set_header Host $host;
        }

        location /notificaciones/api/ {
            proxy_pass http://servicio_notificaciones:3005/api/;
            proxy_set_header Host $host;
        }

        location /analitica/api/ {
            proxy_pass http://servicio_analitica:3006/api/;
            proxy_set_header Host $host;
        }
    }
}
